const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.qrcode,
		C3.Plugins.TextBox,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Pin_1: 0},
	{Pin_2: 0},
	{Pin_3: 0},
	{Pin_4: 0},
	{Touch: 0},
	{ID: 0},
	{Scroller: 0},
	{осова: 0},
	{маршруты: 0},
	{карты: 0},
	{магазин: 0},
	{меню: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{QRкод: 0},
	{Спрайт3: 0},
	{моибилеты: 0},
	{назад: 0},
	{Спрайт4: 0},
	{МАРШРУТТЕКСТ: 0},
	{ВПЕМЯТЕКСТ: 0},
	{КОДПРОВЕРКИ: 0},
	{НОМЕРТЕКСТ: 0},
	{ЦЕНА: 0},
	{маршрут: 0},
	{номер: 0},
	{дата: 0},
	{проезд: 0},
	{кодпров: 0},
	{видимсть: 0},
	{Спрайт5: 0},
	{админр: 0},
	{ВводТекста: 0},
	{ГлМеню1: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{MyProfy1: 0},
	{Спрайт8: 0},
	{МойГород: 0},
	{Безапасность: 0},
	{OFF_Tuch_ID: 0},
	{On_Tuch_ID: 0},
	{Меню_Настройки_Приложения: 0},
	{Точки_Обслуживания: 0},
	{Баланс: 0},
	{Баланс100: 0},
	{назад2: 0},
	{key_1: 0},
	{key_2: 0},
	{key_3: 0},
	{key_4: 0},
	{key_5: 0},
	{key_6: 0},
	{key_7: 0},
	{key_8: 0},
	{key_9: 0},
	{key_Back: 0},
	{key_0: 0},
	{Клавиатура: 0},
	{onay_icon: 0},
	{login_Text_Биометрия_Или_Код_Доступа: 0},
	{login_Text_Забыли_код_доступа: 0},
	{login_СПРАЙТ_Забыли_код_доступа: 0},
	{M_Маршруты_icon: 0},
	{M_Карты_icon: 0},
	{M_Магазин_icon: 0},
	{M_Меню_icon: 0},
	{M_Мои_Билеты_icon: 0},
	{M_QNAY_QR_icon: 0},
	{M_Оплатить_по_коду_icon: 0},
	{M_История_Билетов_icon: 0},
	{M_Перевести_icon: 0},
	{M_Пополнить_icon: 0},
	{M_my_cart_icon: 0},
	{M_Другие_Карты_icon: 0},
	{M_Virtual_Cart_icon: 0},
	{M_plus_Virt_Cart: 0},
	{M_Мои_Билеты_text: 0},
	{M_ONAY_QR_text: 0},
	{M_Оплатить_по_коду_text: 0},
	{M_История_билетов_text: 0},
	{M_Перевести_text: 0},
	{M_Пополнить_text: 0},
	{Menu_Virtual_Cart: 0},
	{Menu_Virtual_cart_Varning: 0},
	{Menu_Cart_Varning_Баланс: 0},
	{Назад_Главная_Страница: 0},
	{Menu_Virtual_Cart_Пополнить_Карту_Пополнить: 0},
	{Назад_В_Virtual_Cart_Menu_incon: 0},
	{Menu_Virtual_Cart_TAP_Пополнить_Карту: 0},
	{Menu_Virt_cart_пополнить_карту_3_icon: 0},
	{menu_Virtual_cart_Пополнение: 0},
	{menu_Virtual_cart_Автопополнение: 0},
	{Текст: 0},
	{Menu_Virtual_cart_Введите_сумму_icon: 0},
	{Menu_V_C_200тг_icon: 0},
	{Menu_V_C_300тг_icon: 0},
	{Menu_V_C_500тг_icon: 0},
	{Menu_V_C_Мин_сум_пополнения_text: 0},
	{Menu_V_C_Комисия0_text: 0},
	{Menu_V_C_Способ_Оплаты_text: 0},
	{Menu_Virtual_Cart_Выберите_способ_icon: 0},
	{Menu_Virtual_Cart_ОПЛАТА_Пополнить_icon: 0},
	{Menu_V_C_Условие_соглашения: 0},
	{Значек_Банк_Карт_icon: 0},
	{Menu_V_C_Сумма_пополнения_пуст_icon: 0},
	{Varning_Упс_Что_то_пошло_не_так: 0},
	{Оплата_по_коду_Разрабатывается: 0},
	{correctPin: 0},
	{correctPin2: 0},
	{savePin: 0}
];

self.InstanceType = {
	Pin_1: class extends self.ITextInstance {},
	Pin_2: class extends self.ITextInstance {},
	Pin_3: class extends self.ITextInstance {},
	Pin_4: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Scroller: class extends self.ISpriteInstance {},
	осова: class extends self.ISpriteInstance {},
	маршруты: class extends self.ISpriteInstance {},
	карты: class extends self.ISpriteInstance {},
	магазин: class extends self.ISpriteInstance {},
	меню: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	QRкод: class extends self.IQRCodeInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	моибилеты: class extends self.ISpriteInstance {},
	назад: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	МАРШРУТТЕКСТ: class extends self.ITextInstance {},
	ВПЕМЯТЕКСТ: class extends self.ITextInstance {},
	КОДПРОВЕРКИ: class extends self.ITextInstance {},
	НОМЕРТЕКСТ: class extends self.ITextInstance {},
	ЦЕНА: class extends self.ITextInstance {},
	маршрут: class extends self.ITextInputInstance {},
	номер: class extends self.ITextInputInstance {},
	дата: class extends self.ITextInputInstance {},
	проезд: class extends self.ITextInputInstance {},
	кодпров: class extends self.ITextInputInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	админр: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	ГлМеню1: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	MyProfy1: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	МойГород: class extends self.ISpriteInstance {},
	Безапасность: class extends self.ISpriteInstance {},
	OFF_Tuch_ID: class extends self.ISpriteInstance {},
	On_Tuch_ID: class extends self.ISpriteInstance {},
	Меню_Настройки_Приложения: class extends self.ISpriteInstance {},
	Точки_Обслуживания: class extends self.ISpriteInstance {},
	Баланс: class extends self.ITextInputInstance {},
	Баланс100: class extends self.ITextInstance {},
	назад2: class extends self.ISpriteInstance {},
	key_1: class extends self.ISpriteInstance {},
	key_2: class extends self.ISpriteInstance {},
	key_3: class extends self.ISpriteInstance {},
	key_4: class extends self.ISpriteInstance {},
	key_5: class extends self.ISpriteInstance {},
	key_6: class extends self.ISpriteInstance {},
	key_7: class extends self.ISpriteInstance {},
	key_8: class extends self.ISpriteInstance {},
	key_9: class extends self.ISpriteInstance {},
	key_Back: class extends self.ISpriteInstance {},
	key_0: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	onay_icon: class extends self.ISpriteInstance {},
	login_Text_Биометрия_Или_Код_Доступа: class extends self.ITextInstance {},
	login_Text_Забыли_код_доступа: class extends self.ITextInstance {},
	login_СПРАЙТ_Забыли_код_доступа: class extends self.ISpriteInstance {},
	M_Маршруты_icon: class extends self.ISpriteInstance {},
	M_Карты_icon: class extends self.ISpriteInstance {},
	M_Магазин_icon: class extends self.ISpriteInstance {},
	M_Меню_icon: class extends self.ISpriteInstance {},
	M_Мои_Билеты_icon: class extends self.ISpriteInstance {},
	M_QNAY_QR_icon: class extends self.ISpriteInstance {},
	M_Оплатить_по_коду_icon: class extends self.ISpriteInstance {},
	M_История_Билетов_icon: class extends self.ISpriteInstance {},
	M_Перевести_icon: class extends self.ISpriteInstance {},
	M_Пополнить_icon: class extends self.ISpriteInstance {},
	M_my_cart_icon: class extends self.ISpriteInstance {},
	M_Другие_Карты_icon: class extends self.ISpriteInstance {},
	M_Virtual_Cart_icon: class extends self.ISpriteInstance {},
	M_plus_Virt_Cart: class extends self.ISpriteInstance {},
	M_Мои_Билеты_text: class extends self.ITextInstance {},
	M_ONAY_QR_text: class extends self.ITextInstance {},
	M_Оплатить_по_коду_text: class extends self.ITextInstance {},
	M_История_билетов_text: class extends self.ITextInstance {},
	M_Перевести_text: class extends self.ITextInstance {},
	M_Пополнить_text: class extends self.ITextInstance {},
	Menu_Virtual_Cart: class extends self.ISpriteInstance {},
	Menu_Virtual_cart_Varning: class extends self.ISpriteInstance {},
	Menu_Cart_Varning_Баланс: class extends self.ISpriteInstance {},
	Назад_Главная_Страница: class extends self.ISpriteInstance {},
	Menu_Virtual_Cart_Пополнить_Карту_Пополнить: class extends self.ISpriteInstance {},
	Назад_В_Virtual_Cart_Menu_incon: class extends self.ISpriteInstance {},
	Menu_Virtual_Cart_TAP_Пополнить_Карту: class extends self.ISpriteInstance {},
	Menu_Virt_cart_пополнить_карту_3_icon: class extends self.ISpriteInstance {},
	menu_Virtual_cart_Пополнение: class extends self.ISpriteInstance {},
	menu_Virtual_cart_Автопополнение: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Menu_Virtual_cart_Введите_сумму_icon: class extends self.ISpriteInstance {},
	Menu_V_C_200тг_icon: class extends self.ISpriteInstance {},
	Menu_V_C_300тг_icon: class extends self.ISpriteInstance {},
	Menu_V_C_500тг_icon: class extends self.ISpriteInstance {},
	Menu_V_C_Мин_сум_пополнения_text: class extends self.ITextInstance {},
	Menu_V_C_Комисия0_text: class extends self.ITextInstance {},
	Menu_V_C_Способ_Оплаты_text: class extends self.ITextInstance {},
	Menu_Virtual_Cart_Выберите_способ_icon: class extends self.ISpriteInstance {},
	Menu_Virtual_Cart_ОПЛАТА_Пополнить_icon: class extends self.ISpriteInstance {},
	Menu_V_C_Условие_соглашения: class extends self.ISpriteInstance {},
	Значек_Банк_Карт_icon: class extends self.ISpriteInstance {},
	Menu_V_C_Сумма_пополнения_пуст_icon: class extends self.ISpriteInstance {},
	Varning_Упс_Что_то_пошло_не_так: class extends self.ISpriteInstance {},
	Оплата_по_коду_Разрабатывается: class extends self.ISpriteInstance {}
}